# Generated by Django 4.2.5 on 2023-09-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identify_card',
            field=models.IntegerField(),
        ),
    ]
