# Generated by Django 4.2.5 on 2023-09-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_identify_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_id',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
