# Generated by Django 4.2.5 on 2023-09-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_mobile_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.city'),
        ),
        migrations.AddField(
            model_name='street',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.district'),
        ),
    ]
