# Generated by Django 4.2.5 on 2023-09-22 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_district_city_id_street_district_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='street_id',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bill_ids',
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.province'),
        ),
    ]
