# Generated by Django 4.2.5 on 2023-09-22 18:34

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_city_id_district_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
