# Generated by Django 4.2.5 on 2023-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('start_time', models.DateField()),
                ('bday', models.DateField(verbose_name='Birth day')),
                ('identify_card', models.CharField()),
            ],
        ),
    ]
