# Generated by Django 4.2.5 on 2023-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_time',
            field=models.DateField(default=1),
        ),
    ]
