# Generated by Django 4.2.5 on 2023-09-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bill_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loyalty_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='points',
            new_name='accumulate_point',
        ),
        migrations.AddField(
            model_name='customer',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, verbose_name='Point exchange')),
                ('cantidad', models.IntegerField()),
                ('expired_time', models.DateTimeField()),
                ('cart', models.ManyToManyField(to='loyalty_app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.bill'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.district'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.street'),
        ),
    ]
