# Generated by Django 4.2.5 on 2023-09-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0002_bill_cart_city_district_phone_province_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_ids',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
