# Generated by Django 4.2.5 on 2023-09-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0003_remove_cart_customer_remove_customer_bill_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_app.category'),
        ),
    ]
