# Generated by Django 4.2.5 on 2023-09-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_app', '0005_rename_cantidad_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
